//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITServiceManagement.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTickets
    {
        public int TicketId { get; set; }
        public System.Guid UserId { get; set; }
        public string Title { get; set; }
        public string description { get; set; }
        public short Status { get; set; }
        public string Priority { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    
        public virtual TicketStatus TicketStatus { get; set; }
        public virtual Users Users { get; set; }
    }
}
