//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITServiceManagement.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.UserTickets = new HashSet<UserTickets>();
        }
    
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public bool Gender { get; set; }
        public string ImageUrl { get; set; }
        public System.DateTime BirthDay { get; set; }
        public string Address { get; set; }
        public System.DateTime InsertTime { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string NationalCode { get; set; }
        public string PasswordHash { get; set; }
        public bool IsLocked { get; set; }
        public Nullable<System.DateTime> LockedTime { get; set; }
        public int EmployeeId { get; set; }
        public short RoleId { get; set; }
    
        public virtual Roles Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserTickets> UserTickets { get; set; }
    }
}
